services:
  app:
    build:
      context: .
    container_name: subscription-xray
    ports:
      - "8000:8000"
    volumes:
      - ./app.log:/app/app.log
      - /etc/x-ui/x-ui.db:/app/x-ui.db
    environment:
      DB_PATCH: "/app/x-ui.db"
      SERVER_ADDRESS: "834572350.duckdns.org"
      SERVER_PORT: "443"
      PUBLIC_KEY: "FNaVxy1hPV40Xtm0OnoxqsxSNuQoLmWILUT6FwsdUmI"
      SID: "c2&spx=%2F"
      SNI: "google.com"
      FP: "safari"
